name: Docs

on:
  merge_group:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - master

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mkdocs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Extract changes for the releases from metainfo.xml
        run: |
          ./scripts/extract-changelog-from-metainfo.py metainfo.xml docs/release-notes.md

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: contour-terminal.org
          CONFIG_FILE: ./mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt


